python filter_cube.py --infile data/outcube_median_022.fits.gz --outfile data/sf2outcube_median_022.fits.gz
python filter_cube.py --infile data/outcube_median_032.fits.gz --outfile data/sf2outcube_median_032.fits.gz
python filter_cube.py --infile data/outcube_median_033.fits.gz --outfile data/sf2outcube_median_033.fits.gz
python filter_cube.py --infile data/outcube_median_034.fits.gz --outfile data/sf2outcube_median_034.fits.gz
python filter_cube.py --infile data/outcube_median_035.fits.gz --outfile data/sf2outcube_median_035.fits.gz
python filter_cube.py --infile data/outcube_median_036.fits.gz --outfile data/sf2outcube_median_036.fits.gz
python filter_cube.py --infile data/outcube_median_037.fits.gz --outfile data/sf2outcube_median_037.fits.gz
python filter_cube.py --infile data/outcube_median_042.fits.gz --outfile data/sf2outcube_median_042.fits.gz
python filter_cube.py --infile data/outcube_median_043.fits.gz --outfile data/sf2outcube_median_043.fits.gz
python filter_cube.py --infile data/outcube_median_044.fits.gz --outfile data/sf2outcube_median_044.fits.gz
python filter_cube.py --infile data/outcube_median_045.fits.gz --outfile data/sf2outcube_median_045.fits.gz
python filter_cube.py --infile data/outcube_median_046.fits.gz --outfile data/sf2outcube_median_046.fits.gz
python filter_cube.py --infile data/outcube_median_073.fits.gz --outfile data/sf2outcube_median_073.fits.gz
python filter_cube.py --infile data/outcube_median_074.fits.gz --outfile data/sf2outcube_median_074.fits.gz
python filter_cube.py --infile data/outcube_median_076.fits.gz --outfile data/sf2outcube_median_076.fits.gz
python filter_cube.py --infile data/outcube_median_083.fits.gz --outfile data/sf2outcube_median_083.fits.gz
python filter_cube.py --infile data/outcube_median_084.fits.gz --outfile data/sf2outcube_median_084.fits.gz
python filter_cube.py --infile data/outcube_median_085.fits.gz --outfile data/sf2outcube_median_085.fits.gz
python filter_cube.py --infile data/outcube_median_086.fits.gz --outfile data/sf2outcube_median_086.fits.gz
python filter_cube.py --infile data/outcube_median_093.fits.gz --outfile data/sf2outcube_median_093.fits.gz
python filter_cube.py --infile data/outcube_median_094.fits.gz --outfile data/sf2outcube_median_094.fits.gz
python filter_cube.py --infile data/outcube_median_096.fits.gz --outfile data/sf2outcube_median_096.fits.gz
python filter_cube.py --infile data/outcube_median_103.fits.gz --outfile data/sf2outcube_median_103.fits.gz
python filter_cube.py --infile data/outcube_median_104.fits.gz --outfile data/sf2outcube_median_104.fits.gz
python filter_cube.py --infile data/outcube_median_105.fits.gz --outfile data/sf2outcube_median_105.fits.gz
python filter_cube.py --infile data/outcube_median_106.fits.gz --outfile data/sf2outcube_median_106.fits.gz
